[general]
import = ["vague/vague.toml"]
live_config_reload = false

[font]
size = 14.5

[cursor.style]
blinking = "Never"

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"
