- source: ~/.zshrc
  destination: zsh/.zshrc
- source: ~/.p10k.zsh
  destination: zsh/.p10k.zsh
- source: ~/.tmux.conf
  destination: tmux/.tmux.conf
- source: ~/.config/helix
  destination: helix/
- source: ~/.config/yazi
  destination: yazi/
- source: ~/.local/bin
  destination: bin/
- source: ~/.gitconfig
  destination: git/.gitconfig
- source: ~/.gitignore_global
  destination: git/.gitignore_global
- source: /mnt/c/Users/skewbik/AppData/Roaming/Code/User/settings.json
  destination: vscode/settings.jsonc
- source: /mnt/c/Users/skewbik/AppData/Roaming/Code/User/keybindings.json
  destination: vscode/keybindings.jsonc
- source: /mnt/c/Users/skewbik/AppData/Roaming/alacritty
  destination: alacritty

