set-option -g allow-passthrough on
set -g mouse off

set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

set -sg escape-time 10

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

set-option -g renumber-windows on
set-option -g status-position bottom

# status bar
set-option -g status-right ""

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

run '~/.tmux/plugins/tpm/tpm'

setw -g mode-keys vi

unbind C-b
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

bind "'" split-window -v -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"

bind-key m select-pane -l \; send-keys C-p Enter \; select-pane -l
