set-option -g allow-passthrough on
set -g mouse off

set -g prefix Insert

set -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",screen-256color:Tc"

set -s escape-time 0

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

set-option -g renumber-windows on
set-option -g status-position bottom

# status bar
set-option -g status-right ""
set -g status-style 'bg=colour235 fg=colour4'

setw -g mode-keys vi

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind-key & kill-window
bind-key x kill-pane

bind ^ last-window
bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

bind -r M-h resize-pane -L 5
bind -r M-j resize-pane -D 5
bind -r M-k resize-pane -U 5
bind -r M-l resize-pane -R 5

bind "'" split-window -v -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"

bind-key m select-pane -l \; send-keys C-p Enter \; select-pane -l

bind S command-prompt -p "New Session:" "new-session -A -s '%%'"
bind K confirm kill-session
